[book]
authors = ["藤浪 大弥 (@makenowjust)"]
language = "ja-JP"
multilingual = false
src = "src"
title = "作って学ぶ正規表現エンジン"

[output.html]
git-repository-url = "https://github.com/makenowjust/kantan-regex-book"
edit-url-template = "https://github.com/makenowjust/kantan-regex-book/edit/main/{path}"
